#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────
#  Pwner - Interactive Setup Script
#  Creates ~/.config/pwner/pwner.conf
# ─────────────────────────────────────────────────────────────
set -euo pipefail

RED='\033[1;31m'
GRN='\033[1;32m'
YLW='\033[1;33m'
BLU='\033[1;34m'
MAG='\033[1;35m'
CYN='\033[1;36m'
DIM='\033[2m'
BOLD='\033[1m'
RST='\033[0m'

info()  { echo -e "${BLU}[*]${RST} $1"; }
ok()    { echo -e "${GRN}[+]${RST} $1"; }
warn()  { echo -e "${YLW}[!]${RST} $1"; }
err()   { echo -e "${RED}[-]${RST} $1"; }

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/pwner"
CONFIG_FILE="$CONFIG_DIR/pwner.conf"

echo -e "${MAG}"
cat << 'EOF'
    ____
   / __ \__      ______  ___  _____
  / /_/ / | /| / / __ \/ _ \/ ___/
 / ____/| |/ |/ / / / /  __/ /
/_/     |__/|__/_/ /_/\___/_/
EOF
echo -e "${RST}"
echo -e "${BOLD}Pwner Setup${RST}\n"

# ── Challenges directory ──
read -rp "$(echo -e "${CYN}Challenge workspace directory${RST} [$HOME/ctf]: ")" CHALLENGES_DIR
CHALLENGES_DIR="${CHALLENGES_DIR:-$HOME/ctf}"
# Expand ~ manually
CHALLENGES_DIR="${CHALLENGES_DIR/#\~/$HOME}"

# ── Decompiler ──
echo ""
echo -e "${CYN}Choose your decompiler:${RST}"
echo "  1) IDA Pro"
echo "  2) Ghidra"
echo "  3) Binary Ninja"
read -rp "Selection [1]: " DECOMP_CHOICE
case "${DECOMP_CHOICE:-1}" in
    1) DECOMPILER="ida" ;;
    2) DECOMPILER="ghidra" ;;
    3) DECOMPILER="binja" ;;
    *) DECOMPILER="ida" ;;
esac

# ── Decompiler path ──
DECOMP_DEFAULT=""
if [ "$DECOMPILER" = "ida" ]; then
    # Try to auto-detect
    for p in /opt/ida/ida64 /opt/idapro/ida64 /opt/ida-free/ida64 "$HOME/ida/ida64" "$HOME/idapro/ida64"; do
        [ -x "$p" ] && DECOMP_DEFAULT="$p" && break
    done
    [ -z "$DECOMP_DEFAULT" ] && DECOMP_DEFAULT="$(which ida64 2>/dev/null || echo '')"
elif [ "$DECOMPILER" = "ghidra" ]; then
    for p in /opt/ghidra/ghidraRun "$HOME/ghidra/ghidraRun"; do
        [ -x "$p" ] && DECOMP_DEFAULT="$p" && break
    done
    [ -z "$DECOMP_DEFAULT" ] && DECOMP_DEFAULT="$(which ghidra 2>/dev/null || echo '')"
elif [ "$DECOMPILER" = "binja" ]; then
    for p in /opt/binaryninja/binaryninja "$HOME/binaryninja/binaryninja"; do
        [ -x "$p" ] && DECOMP_DEFAULT="$p" && break
    done
fi

echo ""
PROMPT="Decompiler binary path"
[ -n "$DECOMP_DEFAULT" ] && PROMPT="$PROMPT [$DECOMP_DEFAULT]"
read -rp "$(echo -e "${CYN}${PROMPT}${RST}: ")" DECOMP_PATH
DECOMP_PATH="${DECOMP_PATH:-$DECOMP_DEFAULT}"
DECOMP_PATH="${DECOMP_PATH/#\~/$HOME}"

# ── Terminal ──
echo ""
TERM_DEFAULT="tmux"
[ -n "${TMUX:-}" ] && TERM_DEFAULT="tmux"
[ -n "${KITTY_PID:-}" ] && TERM_DEFAULT="kitty"
read -rp "$(echo -e "${CYN}Terminal multiplexer${RST} [$TERM_DEFAULT] (tmux/kitty/alacritty/wezterm): ")" TERMINAL
TERMINAL="${TERMINAL:-$TERM_DEFAULT}"

# ── GDB plugin ──
echo ""
GDB_DEFAULT="pwndbg"
command -v gef >/dev/null 2>&1 && GDB_DEFAULT="gef"
read -rp "$(echo -e "${CYN}GDB plugin${RST} [$GDB_DEFAULT] (pwndbg/gef/vanilla): ")" GDB_PLUGIN
GDB_PLUGIN="${GDB_PLUGIN:-$GDB_DEFAULT}"

# ── Editor ──
echo ""
EDITOR_DEFAULT="${EDITOR:-nvim}"
read -rp "$(echo -e "${CYN}Preferred editor${RST} [$EDITOR_DEFAULT]: ")" EDITOR_CHOICE
EDITOR_CHOICE="${EDITOR_CHOICE:-$EDITOR_DEFAULT}"

# ── Write config ──
mkdir -p "$CONFIG_DIR"
cat > "$CONFIG_FILE" << CONF
# Pwner Configuration
# Generated by setup.sh on $(date)

# Base directory for challenge workspaces
challenges_dir=$CHALLENGES_DIR

# Decompiler (ida, ghidra, binja)
decompiler=$DECOMPILER

# Full path to decompiler binary
decompiler_path=$DECOMP_PATH

# Terminal for GDB (tmux, kitty, alacritty, wezterm, gnome-terminal)
terminal=$TERMINAL

# GDB plugin (pwndbg, gef, vanilla)
gdb_plugin=$GDB_PLUGIN

# Preferred editor
editor=$EDITOR_CHOICE
CONF

echo ""
ok "Config written to: $CONFIG_FILE"

# ── Create challenges directory ──
mkdir -p "$CHALLENGES_DIR"
ok "Challenges directory ready: $CHALLENGES_DIR"

# ── Check dependencies ──
echo ""
info "Checking dependencies..."
MISSING=0

check_dep() {
    if command -v "$1" >/dev/null 2>&1; then
        ok "$1 found"
    else
        if [ "$3" = "required" ]; then
            err "$1 NOT found (install: $2)"
            MISSING=1
        else
            warn "$1 not found (optional, install: $2)"
        fi
    fi
}

check_dep "patchelf"   "sudo apt install patchelf"      "required"
check_dep "python3"    "sudo apt install python3"        "required"
check_dep "curl"       "sudo apt install curl"           "required"
check_dep "file"       "sudo apt install file"           "optional"
check_dep "strings"    "sudo apt install binutils"       "optional"
check_dep "readelf"    "sudo apt install binutils"       "optional"

# Check pwntools
if python3 -c "import pwn" 2>/dev/null; then
    ok "pwntools found"
else
    err "pwntools NOT found (pip3 install pwntools)"
    MISSING=1
fi

# Check decompiler
if [ -n "$DECOMP_PATH" ] && [ -x "$DECOMP_PATH" ]; then
    ok "$DECOMPILER found at $DECOMP_PATH"
elif command -v "$DECOMPILER" >/dev/null 2>&1 || command -v "${DECOMPILER}64" >/dev/null 2>&1; then
    ok "$DECOMPILER found in PATH"
else
    warn "$DECOMPILER not found (set path manually in config)"
fi

echo ""
if [ "$MISSING" -eq 0 ]; then
    ok "All required dependencies satisfied!"
else
    warn "Some dependencies are missing. Install them for full functionality."
fi

echo ""
info "Setup complete. Build Pwner with: ./install.sh"
